### ISSUE TITLE
import error no data_helper to import 

### ISSUE THREAD

**Issue by dilipbobby** [vidhiJain/Deep-learning-for-sentiment-analysis#1]
I want to re-run your emotion code but it is throwing me error saying no data_helper to import.please let me know from can I get that.

**Comment by vidhiJain** [comment]
Sorry, that file was buggy and related code is lost. That file was not supposed to be in this repository. You can find related code in some of the repositories like https://github.com/huazhisong/TextCNN and https://github.com/CodingForMoney/textcnn
